### ISSUE TITLE
Growatt Hybrid high voltage / Pylontech BMS high voltage (powercube x1) / CAN

### ISSUE THREAD

**Issue by solsrvolt** [ai-republic/bms-to-inverter#11]
Hi,
great work. Thx.
A quick question, support your converter the Growatt SPH Hybrid (HV) series and the Pylontech HV BMS system (powercube X1) over CAN?
Thanks for your response.
Best regards
Utz

**Comment by ai-republic** [comment]
Hi,
yes, I'm sure I can support this. As far as I know, the Growatt inverters use the Pylontech CAN specification.
But if you could get the CAN specifications from the manufacturers then I can tell for sure or - if it differs - implement the module in a couple of days.

**Comment by solsrvolt** [comment]
Hi,
thanks for your quick reply. I attached the high voltage protocol and some other files for this setup (Growatt SPH Hybrid (HV) series and the Pylontech HV BMS system (powercube X1)) . It`s very hard to get the Growatt can bus protocol from the manufacturer. Maybe it will help you.
Many thanks for your support.
Best regads Utz
[pylon_CAN_210124.txt](https://github.com/ai-republic/bms-to-inverter/files/14157972/pylon_CAN_210124.txt)
[CAN-Bus-Protocol-Sermatec-high-voltage-V1.1810kW (1).pdf](https://github.com/ai-republic/bms-to-inverter/files/14157973/CAN-Bus-Protocol-Sermatec-high-voltage-V1.1810kW.1.pdf)
[PYLONTECH.zip](https://github.com/ai-republic/bms-to-inverter/files/14157974/PYLONTECH.zip)

**Comment by ai-republic** [comment]
Ok, I will have a look at it possibly this week.
The file _[CAN-Bus-Protocol-Sermatec-high-voltage-V1.1810kW (1).pdf](https://github.com/ai-republic/bms-to-inverter/files/14157973/CAN-Bus-Protocol-Sermatec-high-voltage-V1.1810kW.1.pdf)_ is the protocol for your Pylontech HV BMS, correct?

**Comment by solsrvolt** [comment]
Hi Torsten,

yes it is. I have attached a document regarding the growatt Can Bus.
Best regards / Utz 
[Growatt-Battery-BMS.docx](https://github.com/ai-republic/bms-to-inverter/files/14166157/Growatt-Battery-BMS.docx)

**Comment by ai-republic** [comment]
Thanks for the sponsoring! :)
I will see what I can implement this weekend starting with the HV BMS support first. Then we can test that we get some proper readings.

**Comment by solsrvolt** [comment]
Hi Torsten,

thanks for your great support. 
I will testing in the next days. Replay comes.

Have nice (rest)weekend.

Best regards Utz

**Comment by ai-republic** [comment]
Ok.  Be sure to connect CAN H and CAN L correctly of your Powercube X1 to the PI hat. 
This is what I found in the Operation Manual for the Powercube X1:
![image](https://github.com/ai-republic/bms-to-inverter/assets/53671587/91d4d688-53f9-45a3-86ba-f1bc9f5857fd)

So you need to cut a RJ45 network cable (min. CAT 5) and connect pin 4 (CANH) to CANH and pin 5 (CANL) to the CANL  on your PI's CAN hat.

Let me know if you have any questions!

**Comment by solsrvolt** [comment]
Hi, thx.
Currently I have a problem, I can only select the daly bms, no any other inverter bms and only "none" inverter brand. I installed the configurator on a pi 4 with JDK, do you have an idea what is the problem?

Thanks. best regrds Utz

**Comment by solsrvolt** [comment]
64-bit, newest PI firmware (bookworm)

**Comment by solsrvolt** [comment]
Hi,
I solved the problem, but I can't chose the bm pylontech hv protocol, see png attached.
Thx. for your support.
BG / Utz
![2024-02-11-172950_2560x1440_scrot](https://github.com/ai-republic/bms-to-inverter/assets/63457948/36952cb6-c6e2-4b16-a833-80cf1c7fa7d9)

**Comment by ai-republic** [comment]
Let me check....

**Comment by solsrvolt** [comment]
merci, I will testing this week and come back with results.
Bg / Utz

**Comment by solsrvolt** [comment]
Hi Tosrten,

I tested, see the result in the attached jpeg. Pls. can you help me?
Thx. BG Utz
![error](https://github.com/ai-republic/bms-to-inverter/assets/63457948/cf41d191-edc3-4ced-9c22-20479f2a81d9)

**Comment by ai-republic** [comment]
Hi Utz,
so far so good, but does it stop after the last log entry?
Is your BMS connected to can1 or can0?
Please use the _Dummy_ inverter for now, so we can test if we get any readings from the BMS.
Also configure the _log level_ to _debug_ in the Configurator please. In the future please just attach the log file found in `<installation directory>/logs` folder. Then it's easier to read ;)

**Comment by solsrvolt** [comment]
Hi Torsten,
I tested, pls. see the attached log. The converter display said "bms com failed". The pylon BMS show no errors on the leds.
I think its not a great problem :-)
Thx. for your support.
BG / Utz
[BMS-to-Inverter-2024-02-12-1.log.gz](https://github.com/ai-republic/bms-to-inverter/files/14319192/BMS-to-Inverter-2024-02-12-1.log.gz)

**Comment by ai-republic** [comment]
Hi Utz,
good, looks like the BMS is responding properly to the request. But something is not right possible with the configuration.
Could you please attach your `config.properties` file from the config folder.

**Comment by jenshermans** [comment]
Hi,
Subscibed to this.
Having the same growatt HV inverter (SPH 5000TL3 BH-UP).
I have the Pylontech Force H1 battery. But I'm guessing I also could use the pylontech_hv_can module.
Attached my config and log file.

[config.txt](https://github.com/ai-republic/bms-to-inverter/files/14322433/config.txt)
[BMS-to-Inverter.log](https://github.com/ai-republic/bms-to-inverter/files/14322434/BMS-to-Inverter.log)

**Comment by solsrvolt** [comment]
Hi Torsten,
in the attachment you find my configuration properties.
Thanks for analysing.
BG Utz
[config.txt](https://github.com/ai-republic/bms-to-inverter/files/14322531/config.txt)

**Comment by ai-republic** [comment]
Hi Utz & Jens,
please update your installation (_Clean install_ in the _Configurator_). 
I've fixed the problem with the exception so you should get some proper readings now. I've tested it on my PI giving it simulated data for the SOC, current and voltage readings.

@jenshermans Please reduce your configuration to a minimum for now (see Utz's config) until we get decent data from the BMSes

**Comment by jenshermans** [comment]
Hi,
Did a clean install, copied the config file from Utz and this is my log file;
[BMS-to-Inverter.log](https://github.com/ai-republic/bms-to-inverter/files/14335251/BMS-to-Inverter.log)

**Comment by solsrvolt** [comment]
Hi Torsten,
here is my clean configuration log file. Now I have some values from the hv pylontechs... , but still errors. The inverter does not recognise the bms.
Thx. BG Utz
[BMS-to-Inverter.txt](https://github.com/ai-republic/bms-to-inverter/files/14335948/BMS-to-Inverter.txt)

**Comment by jenshermans** [comment]
Hi Torsten,
I'v added my current log on debug level, Doubting it's an other Pylontech HV protocol...
For the growatt inverter; I can't set any protocols on my SPH, even on installer level.
[BMS-to-Inverter.log](https://github.com/ai-republic/bms-to-inverter/files/14339285/BMS-to-Inverter.log)

**Comment by ai-republic** [comment]
Hi,
thanks for the log.
Could you check which protocols or batteries your inverter supports (maybe in the manual or website)? 
Maybe you could also ask Growatt to send you a list of supported batteries or even better their CAN protocol ;)
What I've found was that that they support(ed?) the Pylontech protocol, so the SolArk should work:
![image](https://github.com/ai-republic/bms-to-inverter/assets/53671587/eacd0a13-ba79-43fa-aa2a-db914aa6c377)

Have you connected the right pins from CAN hat to inverter to your `can1` port?
![image](https://github.com/ai-republic/bms-to-inverter/assets/53671587/d0f7ba75-e52f-42b5-bd21-368e1de8128f)

**Comment by solsrvolt** [comment]
Hi Torsten,

that's tricky, Growatt supported the Pylontech Powercube X1 when the SPH bh-up inverter series was launched. Growatt has not officially supported the memory for some time now. But it still works. A friend is running this setup with the Pylontech CAN protocol 1.18 (see above). I think I read somewhere that Growatt uses the CAN bus protocol 1.01 (that's not open) for the high-voltage series.
I'll check the SolArk settings again today.
BG / Utz

Translated with DeepL.com (free version)

**Comment by solsrvolt** [comment]
Hi,
I tested three ways: Growatt-Pylon, SolArk-HVPylon, SolArk-Pylon. Logs attached.
Bg / Utz
[BMS-to-Inverter-Growatt-Pylon.log](https://github.com/ai-republic/bms-to-inverter/files/14342249/BMS-to-Inverter-Growatt-Pylon.log)
[BMS-to-Inverter-SolArk-HVPylon.log](https://github.com/ai-republic/bms-to-inverter/files/14342250/BMS-to-Inverter-SolArk-HVPylon.log)
[BMS-to-Inverter-SolArk-Pylon.log](https://github.com/ai-republic/bms-to-inverter/files/14342251/BMS-to-Inverter-SolArk-Pylon.log)

**Comment by jenshermans** [comment]
Hi,

I'm receiving packages from my growatt inverter, uploaded my candump. maybe this could help you a little forward.
Alsof tried the (new) configuration with pylonHV-Growatt and PylonHV-SolArk, logfiles are also added as attachment.
Also found this similar project documents regarding 
 the Growatt inverter. (jk-bms); https://drive.google.com/drive/folders/1YP-UwRgFRqus0CKmYnccU79ZlMlZN57e

[candump.log](https://github.com/ai-republic/bms-to-inverter/files/14348929/candump.log)
[PylonHV_Growatt.log](https://github.com/ai-republic/bms-to-inverter/files/14348930/PylonHV_Growatt.log)
[PylonHV_Solark.log](https://github.com/ai-republic/bms-to-inverter/files/14348932/PylonHV_Solark.log)

**Comment by sanitariu** [comment]
Here is a link with the protocol information for low an high voltage 
https://www.amosplanet.org/how-to-commission-the-communication-between-lithium-ion-battery-and-spf-3500-5000es/


https://www.amosplanet.org/wp-content/uploads/2022/04/Growatt_BMS_RS485_protocal_1xSxxP_ESS_V2.02-1.pdf

https://www.amosplanet.org/wp-content/uploads/2022/04/Growatt-BMS-CAN-Bus-protocol-low-voltage-V1.04-1.pdf

**Comment by ai-republic** [comment]
Hi
I fixed the missing dependency for the Pylontech HV inverter now. Please pulll the latest _Configurator_ and do a _clean install_.

**Comment by jenshermans** [comment]
Hey Torsten,
Downloaded the new files, and the configurator wont open anymore.

**Comment by ai-republic** [comment]
Sorry, my bad! Shouldn't do stuff at 11pm :(

Fixed the service descriptors - now it working.

**Comment by jenshermans** [comment]
Added the current log.
I hear the BMS relay clicking, and the status led turned blue, so he goes out of error mode.
On the inverter i now get 'batt voltage high'.

my config is:
-bms: pylon_hv_can
-inverter: pylon_hv_can
[BMS-to-Inverter.log](https://github.com/ai-republic/bms-to-inverter/files/14368775/BMS-to-Inverter.log)

**Comment by ai-republic** [comment]
Hi Jens & Utz,
I just committed a full implementation of the Pylontech HV inverter module (also corrected some value units). 
Could you please test? Thanks!

**Comment by jenshermans** [comment]
BMS reading looks right. Inverter now shows 'bms com fault'.

[BMS-to-Inverter.log](https://github.com/ai-republic/bms-to-inverter/files/14377507/BMS-to-Inverter.log)
[candump bms.log](https://github.com/ai-republic/bms-to-inverter/files/14377508/candump.bms.log)
[candump inverter.log](https://github.com/ai-republic/bms-to-inverter/files/14377509/candump.inverter.log)

**Comment by ai-republic** [comment]
Hi Jens,
I fixed some wrong units. Hopefully that will solve the 'bat voltage high'.
Can you please test the latest version?

**Comment by jenshermans** [comment]
Current logs attached, Inverter still shows bat voltage high, bms com fault
[BMS-to-Inverter.log](https://github.com/ai-republic/bms-to-inverter/files/14381828/BMS-to-Inverter.log)

**Comment by ai-republic** [comment]
Hi Jens,
I'm a little bit confused about your battery configuration.
When I send a broadcast to all battery modules I only receive answers from Battery No. 2 (e.g. 0x4211) but not from Battery No. 1 (e.g. 0x4210). Last digit identifies the battery module. 

On Utz's battery I get the correct Battery No. 1 (e.g. 0x4210) when doing the broadcast.
Could it be that you need to change the DIP switch on your BMS or Battery module to correct the identifer?

When the inverter starts a broadcast to request the BMS data, I now send data from all BMS. 

So I updated some code for more info. Maybe you can update and run it again?

**Comment by solsrvolt** [comment]
Hi Torsten,
I tested, the inverter display dispatch BMS Abnormal, BMS Com fault. Can you provide me with the version that worked for Jens until the inverter/bms stopped using bms com fault, bat voltage high? The Powercube BMS schows a red error light.
Thx.
BG/Utz
[BMS-to-Inverter.log](https://github.com/ai-republic/bms-to-inverter/files/14387596/BMS-to-Inverter.log)

**Comment by jenshermans** [comment]
Hi Torsten,
It's not possible to change my BMS address, this addresses itself. Its only possible to change bitrate and some "special protocols"
For this current version; Battery is okay and the inverter is showing the first 5 seconds "normal", after that it shows 'BMS com fault' and 'Normal' varying.
But i noticed; the first 5 seconds, (while normal) the SOC is displaying like it should be, after that it disappears.

Did a candump on can0 and can1 (starting from timestamp 2024-02-23 17:36:07.064 in the bms-to-inverter log)

[BMS-to-Inverter.log](https://github.com/ai-republic/bms-to-inverter/files/14387765/BMS-to-Inverter.log)
[candump can0 bms.log](https://github.com/ai-republic/bms-to-inverter/files/14387766/candump.can0.bms.log)
[candump can1 inv.log](https://github.com/ai-republic/bms-to-inverter/files/14387767/candump.can1.inv.log)

**Comment by ai-republic** [comment]
Hi Utz,
can you please update to the latest version. You seem to not get any responses from your BMS. Please also check that your CAN device is properly connected and that the BMS is not idle.

**Comment by ai-republic** [comment]
Hi Jens,
from the candump can1 (inverter) I can see that everything gets sent to the inverter initially. Then 5 seconds between the sending of the invalid data of 0x4210 and then the valid data 0x4211, etc.

I have fixed that temporarily ignoring the battery for which I don't get data (0x4210 in your case). That should hopefully fix the problem that the inverter switches from normal to error mode.

**Comment by jenshermans** [comment]
Hi Torsten,

I'm still getting the bms com error on the inverter, in the logs you also will see 'error communicating to inverter'.
[BMS-to-Inverter.log](https://github.com/ai-republic/bms-to-inverter/files/14392014/BMS-to-Inverter.log)

**Comment by ai-republic** [comment]
Hi Jens,
I fixed the exception when sending of the manufacturer.

**Comment by jenshermans** [comment]
Still receiving the 'normal/bms com error' status
added a candump of the inverter to attachments. 
[BMS-to-Inverter.log](https://github.com/ai-republic/bms-to-inverter/files/14392048/BMS-to-Inverter.log)
[candump-inv.log](https://github.com/ai-republic/bms-to-inverter/files/14392050/candump-inv.log)

**Comment by ai-republic** [comment]
hmm, can you access the inverter's log. Maybe there a more detailed error message

**Comment by jenshermans** [comment]
Hope I can help you with this? (via oss.growatt.com)
[Schermafbeelding 2024-02-24 082850](https://github.com/ai-republic/bms-to-inverter/assets/60035424/ca36637d-6157-48a5-9625-35e74a22a356)

**Comment by ai-republic** [comment]
Ok, can you tell me your inverter settings for the maximum voltage limit?

**Comment by jenshermans** [comment]
As the manual describes, battery voltage range is 100-550vdc.

Running your program unlocks my BMS. So I configured the inverter with lead acid battery and its correct charging current/voltage, and load current/voltage. This works fine.

On lithium mode i cant configure anything as all data comes from the BMS.
I noticed something (don't know if this is the problem) Max charging/discharging current is 25A, bms reports via CAN max charge/discharge 37A

[image](https://github.com/ai-republic/bms-to-inverter/assets/60035424/566a2c40-1c4f-4712-861f-89927dbbf2c2)

**Comment by ai-republic** [comment]
Hi,
I updated the Configurator to allow setting a BMS Id. Also I changed the poll intervall to be a general BMS configuration (not for each).

You will need to download the new Configurator and re-configure your setup and do a clean install.

**Comment by ai-republic** [comment]
I also fixed the reading of the module voltages. It was the wrong data type (s_int_16 instead of u_int_16).
They reported -15.608V. I fixed that so now its 49.950V so ~50V for a module.

**Comment by jenshermans** [comment]
Still receiving the BMS com error. Also added my BMS's data this time. maybe this also can help you.
[BMS-to-Inverter.log](https://github.com/ai-republic/bms-to-inverter/files/14395265/BMS-to-Inverter.log)
![image](https://github.com/ai-republic/bms-to-inverter/assets/60035424/eafc3266-a21f-479a-aa93-3c93321f1bc6)
[Screenshot_20240225-055800](https://github.com/ai-republic/bms-to-inverter/assets/60035424/20fa29ea-9af7-4bae-aa71-18daf0f10d22)

**Comment by jenshermans** [comment]
Hey Thorsten,

Please note previous screenshot was from my BMS, it has a WiFi module in-built to read this data.

Added a screenshot of the inverter data. 

Can't read any data from the installer app because there is "no BMC connected"

Also added a picture of the BMS specs. I noticed that growatt wants to display the SN of the battery. Don't know if you send this already, but looks like it could be needed.

![Screenshot_20240225-080735](https://github.com/ai-republic/bms-to-inverter/assets/60035424/7d6eb749-9c29-48e2-9658-f354774169f6)


![Screenshot_20240225-075557](https://github.com/ai-republic/bms-to-inverter/assets/60035424/c70838b2-0f71-4dc0-9b30-30db6a7e2d7a)

![MVIMG_20240225_081011](https://github.com/ai-republic/bms-to-inverter/assets/60035424/3311b69b-da30-49a1-8e0e-747aec95b85f)

**Comment by jenshermans** [comment]
Added error logs from the growatt app,  it refers to specific bytes
![Screenshot_20240225-082833](https://github.com/ai-republic/bms-to-inverter/assets/60035424/b649041f-32d2-4344-b92d-c8029924e745)
![Screenshot_20240225-082810](https://github.com/ai-republic/bms-to-inverter/assets/60035424/8451a448-45df-4fc3-8f9f-e979902497ff)
![Screenshot_20240225-082723](https://github.com/ai-republic/bms-to-inverter/assets/60035424/72c1a25b-fc8e-441d-bc7e-6d69de7573e4)

**Comment by ai-republic** [comment]
@jenshermans I've added sending the 0x42B0 message

What is the baudrate you set for your `can1` to the inverter?

**Comment by jenshermans** [comment]
Running my inverter and BMS at 500kbps
My can startup commands;
```
sudo ip link set can0 up type can bitrate 500000
sudo ip link set can1 up type can bitrate 500000
```

**Comment by ai-republic** [comment]
That should be ok then.

**Comment by ai-republic** [comment]
Could you please update (clean install). I've changed the inverter binding, so that it will send the messages to the inverter always as 0x42x0 (like 0x4210) instead of 0x42xx (like 0x4211). Let's see if Growatt will accept these.

**Comment by jenshermans** [comment]
current log, there is an error communicating to the inverter
[BMS-to-Inverter.log](https://github.com/ai-republic/bms-to-inverter/files/14395642/BMS-to-Inverter.log)

**Comment by ai-republic** [comment]
You're `can1` is not connected or needs to be reset:

```
sudo ip link set can1 down
sudo ip link set can1 up type can bitrate 500000
```

**Comment by ai-republic** [comment]
Wow! Great!!! Awesome!

Still don't know why your BMS sends the 0x421x, etc. messages. If you would have two or more packs that would be understandable. Musst be some internal preconfigured switch....
I'll need to restructure some code to compensate for this in the future.

@solsrvolt Can you confirm that its working for you too?

**Comment by ai-republic** [comment]
@jenshermans Please monitor it for a day or so that everything works as expected. And if you are happy with my work and support please feel free to [sponsor](https://github.com/sponsors/ai-republic) me ;)

**Comment by jenshermans** [comment]
I completely dont have any idea... I can only change the rs485 bitrate and some special protocols, but you have to contact Pylontech for these settings.. BMS addressing goes automatically when plugging in the link cables... 

You can tag me to test your code out when needed. 

Surely going to sponsor you! You made me a happy man, haha!
Thanks for all your work.

**Comment by ai-republic** [comment]
Thanks a lot for your good support too!

**Comment by ai-republic** [comment]
Oh, and don't forget to turn down the log-level to _info_ or _warning_ when you finished monitoring. Feel free to open an issue if something is not working properly.

And many thanks for sponsoring this project!

**Comment by solsrvolt** [comment]
Hi Torsten,
a quick response, today I started the new configurator file, it seems that it works good withe power cube X1. Great work, I will checking for the next days and going to sponsor you. Top.
Bg/ Utz

**Comment by ai-republic** [comment]
Excellent! Very pleased to hear that :)
Just get back to me if you have any issues or need support.
Sponsors are always very welcome ;)

**Comment by solsrvolt** [comment]
Hi Torsten,
I have now been able to test the converter extensively.
There is still a small bug: if the batteries are charged by the sun, but the sun is not sufficient for heavy current loads (e.g. cooker), the battery does not supply the missing current to the house grid. I believe that this fault can be rectified quickly. 
@jenshermans, do you have the same problem?
Thanks to all, for support.
BG/Utz

**Comment by ai-republic** [comment]
Hi Utz,
but that sounds like a configuration on your inverter to use e.g. battery first over the utility grid. 
I'm not sure there's anything I can do from my side. There's no BMS command to tell the inverter where to draw its power from (wouldn't make any sense either).
The only other thing I could think of would be the maximum discharge current (Amps) set in the BMS.
But maybe @jenshermans has an idea or observation?

**Comment by jenshermans** [comment]
Hi, 
I also noticed this but like Torsten is saying, probably nothing he can do.
How I solved this problem is limiting my max charging SOC; configuring to 98 seems to work for me.
Also set your discharging soc to 10% or something like that. Because when you want to charge you get te same effect (if you had'nt noticed already).

Probably your battery priority is set right, because else it won't take any watt from your battery.

**Comment by solsrvolt** [comment]
Hi,
I solved the problem with the settings mentioned by Jens.
Thanks for for all your support.
BG Utz

**Comment by solsrvolt** [comment]
Hi Torsten,
thanks again for the converter. I have been using the converter since March. It works great. 
However, I have noticed one small thing, at night when the house consumption is fed from the battery, the battery always supplies on average 200 watts more power than the house needs in terms of load. The surplus power from the battery is fed into the public power grid and causes the battery to discharge more quickly. Example: House load = 250 watts, battery supplies 450 watts, the difference of 200 watts is fed into the public electricity grid.
Is it possible to reduce this value to approx. 30 - 50 watts (possibly dropdown field ) or as a fixed value?
Many thanks to your support.
BG / Utz

**Comment by ai-republic** [comment]
Hi Utz,
I guess you need to configure that directly on the inverter as there is no commands to steer that via the CAN messages.
Just check the manual of your inverter for the correct setting.

Best regards,
Torsten

**Comment by jenshermans** [comment]
Hi,
I checked this and its there is indeed an continuous export (140-150watts)
![image](https://github.com/ai-republic/bms-to-inverter/assets/60035424/c6eae8e6-c5a7-4712-8a97-302795d8c353)

My latest build without the export current was on 25/02, this is the one showing all BMS's 
![image](https://github.com/ai-republic/bms-to-inverter/assets/60035424/711309c9-c29c-45a3-9ac2-c6717da8acc9)

Logfile of latest version (downloaded today)
[BMS-to-Inverter.log](https://github.com/ai-republic/bms-to-inverter/files/15137094/BMS-to-Inverter.log)

**Comment by ai-republic** [comment]
Hi Jens,
there is nothing I can do from my side to control the inverter to not export to the grid or to set a threshold when to export. That must be done in the inverter's configuration itself. Maybe there was an update of the inverter's firmware that's causing this?

**Comment by jenshermans** [comment]
Hi,
I used the version of 25/02 and working without any (export) issue from my previous post till now. so i'm thinking it's not on the inverter side.. Maybe a calculation error when selecting the right BMS?
I'm guessing it would be amps, the difference is more or less -1A.

I think the BMS sends a feedback of its amps to the inverter, and the inverter is trying to correct this but without success

**Comment by ai-republic** [comment]
Hmm,the app sends the values I get via CAN to the inverter but unless there's a interpetetion error. That should be fine. And I haven't changed anything there. Maybe when aggregating the values from both BMSes?But exporting to the grid is nothing I can control.I'll check the log and see what total current is sent to the inverter tomorrow On 27/4/24, 17:06 Jens Hermans ***@***.***> wrote:

   
  Hi, I used the version of 25/02 and working without any (export) issue from my previous post till now. so i'm thinking it's not on the inverter side.. Maybe a calculation error when selecting the right BMS? I'm guessing it would be amps, the difference is more or less -1A. 
  I think the BMS sends a feedback of its amps to the inverter, and the inverter is trying to correct this but without success

**Comment by solsrvolt** [comment]
> Hi, I used the version of 25/02 and working without any (export) issue from my previous post till now. so i'm thinking it's not on the inverter side.. Maybe a calculation error when selecting the right BMS? I'm guessing it would be amps, the difference is more or less -1A.
> 
> I think the BMS sends a feedback of its amps to the inverter, and the inverter is trying to correct this but without success

Hi Jens, do you have other configurator versions after the version from 25.02. and the latest? Can you provide me with this version. I will test ist. Thanks. BG Utz

**Comment by ai-republic** [comment]
I checked the log and the implementation, but it sends the correct amps (0.0A) which is reported by the BMS to the inverter.
Did you check if the firmware of the inverter was updated (maybe automatically) and maybe some ratio setting for the grid export has changed?

**Comment by jenshermans** [comment]
These are all the versions i have, tested all of them.
All config files are configured the same. no inverter settings where changed during this test

25/02 1:
reading all BMS, no SOC to inverter
[BMS-to-Inverter 25-02-1.log](https://github.com/ai-republic/bms-to-inverter/files/15140805/BMS-to-Inverter.25-02-1.log)

25/02 2:
Reading all BMS, Posting SOC to inverter, drawing correct current from battery
[BMS-to-Inverter 25-02-2.log](https://github.com/ai-republic/bms-to-inverter/files/15140822/BMS-to-Inverter.25-02-2.log)

26/02 1
Error
[BMS-to-Inverter 26-02-1.log](https://github.com/ai-republic/bms-to-inverter/files/15140829/BMS-to-Inverter.26-02-1.log)

27/02 2
Reading all BMS, Posting SOC to inverter, drawing correct current from battery
[BMS-to-Inverter-26-02-2.log](https://github.com/ai-republic/bms-to-inverter/files/15140839/BMS-to-Inverter-26-02-2.log)

27/02 1
Reading all BMS, Posting SOC to inverter, exporting 140-150w
[BMS-to-Inverter 27-02-1.log](https://github.com/ai-republic/bms-to-inverter/files/15140854/BMS-to-Inverter.27-02-1.log)

**Comment by ai-republic** [comment]
Ok, thanks Jens.

I will check through the commits from 26.02. to 27.02. and see if I can find anything.

**Comment by ai-republic** [comment]
@jenshermans I have committed a change about the forbidden charge/discharge flags that were changed in the commit from 26.04. but I'm not sure if that has any effect on your inverter.
Could you try this please?

**Comment by solsrvolt** [comment]
@Torsten, the inverter display BMS Abnormal, see log attached
[30.04.2024_BMS-to-Inverter.log](https://github.com/ai-republic/bms-to-inverter/files/15165961/30.04.2024_BMS-to-Inverter.log)

**Comment by ai-republic** [comment]
I fixed it, but still implementing a fix for the webserver too. I should be finished with that later on in the day :)

**Comment by jenshermans** [comment]
Hi torsten,
Tested current version. Looks like it's not drawing any power because it reports a lot of bms alarms I guess.
[BMS-to-Inverter-01-05-1.log](https://github.com/ai-republic/bms-to-inverter/files/15173908/BMS-to-Inverter-01-05-1.log)

**Comment by ai-republic** [comment]
Hi Utz and Jens,
could you please test the new version. I fixed the alarms and also corrected the forbidden dis-/charge flags.

**Comment by jenshermans** [comment]
Hi Torsten,
It doesnt draw any current from the battery
[BMS-to-Inverter-01-05-2.log](https://github.com/ai-republic/bms-to-inverter/files/15174475/BMS-to-Inverter-01-05-2.log)

**Comment by ai-republic** [comment]
hmm, I reverted the change with the forbidden flags please test again

**Comment by solsrvolt** [comment]
Hi Torsten, it works but the same, a continious export (170-200 Watt) to the grid. I didn`t change anything in the settings from the inverter. BG Utz
[01.05.2024-BMS-to-Inverter.log](https://github.com/ai-republic/bms-to-inverter/files/15175462/01.05.2024-BMS-to-Inverter.log)

**Comment by ai-republic** [comment]
Hmm, so it wasn't those flags - didn't think so. The only other thing that changed was that the values are aggregated, but with only 1 BMS it doesn't have any averages, etc.
The other thing we changed was from separately requesting the values to requesting the values all at once. But the values are the same and not different. I will compare the logs again and see if I find any difference in the 26.2. and 27.2. logs

**Comment by solsrvolt** [comment]
Hi, thx. BG / Utz

**Comment by solsrvolt** [comment]
Hi Torsten, I noticed, that the battery don`t stopp with charching. At 99% charching, the battery permanently export 100 Watt to the grid.
![Screenshot_20240501_112306_ShinePhone](https://github.com/ai-republic/bms-to-inverter/assets/63457948/d4d8eb46-7c0b-4dbd-b78d-9f608c6cb39d)

**Comment by ai-republic** [comment]
Hi Utz,
I'm not sure that's bad if the batteries are already 99% charged. It discharges with 0.1kW, probably to protect it from overcharging. How does it look like when the battery is charged at 90%?

**Comment by jenshermans** [comment]
Hi Torsten,
Thanks for the 'reminder', these are the logs of current version. Looks like it's not working like it should be. 
In this case the battery keeps discharging, while it should be charging.
[BMS-to-Inverter 0405-1.log](https://github.com/ai-republic/bms-to-inverter/files/15208130/BMS-to-Inverter.0405-1.log)
![image](https://github.com/ai-republic/bms-to-inverter/assets/60035424/78c92fda-7d26-4bb1-9bcd-e502a18de6ae)

**Comment by ai-republic** [comment]
Hi Jens,
I've checked your log and saw that the dis-/charge forbidden flags were printed out wrong. I've adjusted the code to reflect that. Also I made an adjustment to compare thees flags as they were not comparing the same data type.

Could you please test it again?

**Comment by jenshermans** [comment]
Hi,
These are my current logs, its exporting current again. (140-150w)
[BMS-to-Inverter-05-05-01.log](https://github.com/ai-republic/bms-to-inverter/files/15211810/BMS-to-Inverter-05-05-01.log)

**Comment by ai-republic** [comment]
hmm, I don't know what I can do about that. My application doesn't tell the inverter anything about grid import or exporting. It only relais the status of the BMS to the inverter. Like SOC, SOH, Voltage, Amps, temperature and alarms. It does not control the inverter.
Unless you can find something in the inverter logs or inverter configuration or the manual why its deciding to export energy I'm not sure I can help. I've checked all the changed between the versions from 25.02.-27.02. and I have found no changes that would relate to such a behaviour.

**Comment by solsrvolt** [comment]
Hi Torsten, I can currently live with the last version (also with the constant grid export of approx. 200 watts and the discharge at 99% battery level). 
If I change the settings e.g. in the inverter to zero export, no more electricity is exported, with 20% export setting it is then the 200 watts again :-) .
However, I also noticed today that the battery continues to discharge when the Soc is set to 20% (stop battery discharge).

@Jens, is this also the case for you?

Many thanks for the great support and work.

BG / Utz

[05.05.2024-BMS-to-Inverter.log](https://github.com/ai-republic/bms-to-inverter/files/15213263/05.05.2024-BMS-to-Inverter.log)

**Comment by ai-republic** [comment]
I think there might be an issue with the Growatt and Pylon communication as decribed in this document:
[Growatt-Battery-BMS.pdf](https://github.com/ai-republic/bms-to-inverter/files/15256967/Growatt-Battery-BMS.pdf)

We would have to try this method to tell the inverter to stop and start charging. I will have to think about this because it will be a special handling of the Pylon HV CAN protocol. I guess I will have to add a special communication plugin that will monitor and change values before they are sent to the inverter

**Comment by ai-republic** [comment]
Closing this issue since I have not heard anything for a long time. Please create a new issue if you encounter any problems.
